name: Terraform Workflow

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0  # Specify the version you want to use
      
    - name: Initialize Terraform
      run: terraform init
      
    - name: Validate Terraform configuration
      run: terraform validate
      env:
        TF_VAR_example_var: value  # Replace with your Terraform variables as needed
      # Add secrets as environment variables for sensitive data, such as AWS credentials
      # env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
